apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-09-23T08:04:48Z"
  labels:
    controller-uid: 3dc83f4f-6a20-4265-b87c-2765c5890043
    job-name: istio-install-job-om1pr
  name: istio-install-job-om1pr
  namespace: istio-system
  resourceVersion: "340292"
  selfLink: /apis/batch/v1/namespaces/istio-system/jobs/istio-install-job-om1pr
  uid: 3dc83f4f-6a20-4265-b87c-2765c5890043
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 3dc83f4f-6a20-4265-b87c-2765c5890043
  template:
    metadata:
      annotations:
        helm.sh/hook-delete-policy: hook-succeeded
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        controller-uid: 3dc83f4f-6a20-4265-b87c-2765c5890043
        job-name: istio-install-job-om1pr
    spec:
      containers:
      - command:
        - /istio/bin/istioctl
        - verify-install
        - -f
        - /istio/install/kubernetes/operator/profiles/install.yaml
        image: 10.0.128.54:60080/asm/asm-istioctl:1.6.5
        imagePullPolicy: IfNotPresent
        name: verify
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /istio/install/kubernetes/operator/profiles
          name: default
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alaudak8s
      initContainers:
      - command:
        - /istio/bin/replace.sh
        - 10.0.128.36:30900
        - /istio/install/kubernetes/operator/default.yaml
        - /istio/install/kubernetes/operator/profiles/default.yaml
        image: 10.0.128.54:60080/asm/asm-istioctl:1.6.5
        imagePullPolicy: IfNotPresent
        name: precheck
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /istio/install/kubernetes/operator/profiles
          name: default
      - command:
        - /istio/bin/generate.sh
        - manifest
        - generate
        - --charts
        - /istio/install/kubernetes/operator
        - --set
        - profile=default
        - --set
        - values.global.labelBaseDomain=cpaas.io
        - --set
        - values.global.hub=10.0.128.54:60080/asm
        - --set
        - values.telemetry.v1.enabled=false
        - --set
        - values.telemetry.v2.enabled=true
        - --set
        - values.grafana.rootUrl=https://10.0.128.54/grafana-asm-openshift
        - --set
        - values.global.proxy.includeIPRanges=*
        - --set
        - values.pilot.traceSampling=100.00
        - --set
        - components.pilot.k8s.replicaCount=1
        - --set
        - components.pilot.k8s.hpaSpec.minReplicas=1
        - --set
        - values.gateways.istio-ingressgateway.replicaCount=1
        - --set
        - values.gateways.istio-ingressgateway.autoscaleMin=1
        - --set
        - values.global.proxy.autoInject=disabled
        - --set
        - values.global.proxy.resources.limits.cpu=100m
        - --set
        - values.global.proxy.resources.limits.memory=128Mi
        - --set
        - values.global.proxy.resources.requests.cpu=100m
        - --set
        - values.global.proxy.resources.requests.memory=128Mi
        - --set
        - values.gateways.istio-egressgateway.enabled=true
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].key=istio
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].values=egressgateway
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].operator=In
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].topologyKey=kubernetes.io/hostname
        - --set
        - values.gateways.istio-egressgateway.autoscaleEnabled=false
        - --set
        - values.gateways.istio-egressgateway.autoscaleMin=2
        image: 10.0.128.54:60080/asm/asm-istioctl:1.6.5
        imagePullPolicy: IfNotPresent
        name: generate
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /istio/install/kubernetes/operator/profiles
          name: default
      - command:
        - /istio/bin/istioctl
        - install
        - --charts
        - /istio/install/kubernetes/operator
        - --set
        - profile=default
        - --set
        - values.global.labelBaseDomain=cpaas.io
        - --set
        - values.global.hub=10.0.128.54:60080/asm
        - --set
        - values.telemetry.v1.enabled=false
        - --set
        - values.telemetry.v2.enabled=true
        - --set
        - values.grafana.rootUrl=https://10.0.128.54/grafana-asm-openshift
        - --set
        - values.global.proxy.includeIPRanges=*
        - --set
        - values.pilot.traceSampling=100.00
        - --set
        - components.pilot.k8s.replicaCount=1
        - --set
        - components.pilot.k8s.hpaSpec.minReplicas=1
        - --set
        - values.gateways.istio-ingressgateway.replicaCount=1
        - --set
        - values.gateways.istio-ingressgateway.autoscaleMin=1
        - --set
        - values.global.proxy.autoInject=disabled
        - --set
        - values.global.proxy.resources.limits.cpu=100m
        - --set
        - values.global.proxy.resources.limits.memory=128Mi
        - --set
        - values.global.proxy.resources.requests.cpu=100m
        - --set
        - values.global.proxy.resources.requests.memory=128Mi
        - --set
        - values.gateways.istio-egressgateway.enabled=true
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].key=istio
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].values=egressgateway
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].operator=In
        - --set
        - values.gateways.istio-egressgateway.podAntiAffinityTermLabelSelector[0].topologyKey=kubernetes.io/hostname
        - --set
        - values.gateways.istio-egressgateway.autoscaleEnabled=false
        - --set
        - values.gateways.istio-egressgateway.autoscaleMin=2
        image: 10.0.128.54:60080/asm/asm-istioctl:1.6.5
        imagePullPolicy: IfNotPresent
        name: apply
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /istio/install/kubernetes/operator/profiles
          name: default
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: servicemesh-istioinstall
      serviceAccountName: servicemesh-istioinstall
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: default
status:
  completionTime: "2020-09-23T08:30:29Z"
  conditions:
  - lastProbeTime: "2020-09-23T08:30:29Z"
    lastTransitionTime: "2020-09-23T08:30:29Z"
    status: "True"
    type: Complete
  startTime: "2020-09-23T08:04:47Z"
  succeeded: 1